### PR TITLE
Update lime.example

### PR DESCRIPTION
**Pull request by ilario**

### CODE REVIEW

**Comment by p4u** [comment]
Please, remove blank lines with spaces or tabs

**Comment by ilario** [comment]
Couldn't find any... I removed some duplicated empty lines [here](/ilario/lime-packages/commit/f0ce9a13cc33e609bf16956acd659884689501e3).

**Comment by ilario** [comment]
There was a merge conflict, now the branch should be ok.

**Comment by ilario** [comment]
Rather than opening again this one I created a new one updated: #79

**Pull request closed without merging**
