### PR TITLE
Added lime-hwd-ground-routing to lime-full

### PR DESCRIPTION
**Pull request by ilario**
Including *lime-hwd-ground-routing* module in lime-full will have no negative impact and will allow to configure [ground routing](http://libre-mesh.org/projects/libre-mesh/wiki/Ground_routing) set-ups.

### CODE REVIEW

**Comment by G10h4ck** [comment]
Have you tested exhaustively if this has side effects on generated configuration with default settings ?
I believe it was not added to lime-full because ground-routing is not contemplated in the default LiMe networking schema (like olsr or bgp), but if you are sure there is no unexpected side effects this can be merged as it doesn't add space consuming extra dependencies like lime-proto-* usually do.
Cheers!

**Comment by G10h4ck** [comment]
Any news ?

**Comment by ilario** [comment]
No, I haven't tested it yet.

**Comment by ilario** [comment]
I tested comparing /overlay and /etc on Libre-Mesh on top of LEDE (compiled using branch develop-lede of lime-build) including or not the lime-hwd-ground-routing package. Without configuring the ground-routing I can see no relevant difference in the observed directories (except some change in latitude and longitude in libremap conf wtf). You can find the directories in study [here](https://uz.sns.it/~ilario/libre-mesh-ground-routing-in-lime-full/).

**Comment by G10h4ck** [comment]
As discussed at LimeCat 2016q3 i have added it as dependency of lime-basic
see 59997b597cef49cd92f51a28a06ffa6a0f61a759

**Pull request closed without merging**
