### PR TITLE
Created package with legacy luci.ip

### PR DESCRIPTION
**Pull request by ilario**
I moved the luci.ip library from LiMe libraries to a standalone package.

I tested this with both OpenWRT Barrier Breaker and OpenWRT Chaos Calmer and it does its work solving #7.

Indeed with Chaos Calmer also the rest of the LiMe system seems working so we should really consider to merge this also in develop branch.

### CODE REVIEW

**Comment by G10h4ck** [comment]
I would remove the term legacy around as there is no reason to have this called legacy, they removed it from Luci only because they didn't use it any-more.

**Comment by ilario** [comment]
Removed the "legacy" terms.

**Comment by G10h4ck** [comment]
Seems fine, when you do more testing please consider to do a merge request of this branch to develop

**Comment by p4u** [comment]
Sorry for appearing probably too late, but I would like to comment anyway.

First of all, let me see that you made a single commit named "Created package with legacy luci.ip " and IMO this information is not correct (you made more changes). Secondly, let me make two suggestions:

- You changed the name of the lua package from lime.ipl to libluciip 
I don't see the need of naming it **luci** because the library does not belong to luci anymore, we have forked it to keep using it, so the name IMO should be something like lime.ip or lime.ipcalc

- You added all the old comments
I deleted all the comments because it increases the size of the file and we don't have that much space to waste on not necessary data. If you want to keep the comments you must write some shell commands to remove them before installing (see other lime Makefiles to have some example)

Finally, thank you for contributing!

**Pull request merged**
