### PR TITLE
Added comments and description for ground routing package

### PR DESCRIPTION
**Pull request by ilario**
I added the description for lime-hwd-ground-routing package and added comments in /etc/config/lime file in ground routing section.

### CODE REVIEW

**Comment by G10h4ck** [comment]
Have you tested it if it compiles and run fine ?

**Comment by ilario** [comment]
The pull request is just about some comments and a description of a package, so it should compile and run just as well as before this commit. Anyway it compiled fine but up to now I have no hardware for testing it.

**Comment by ilario** [comment]
In the Makefile in the URL: field we have to put the homepage http://libre-mesh.org or we could put the module specific page http://libre-mesh.org/projects/libre-mesh/wiki/Ground_routing ?

**Comment by G10h4ck** [comment]
It seems a good idea to point to the specific page for this package

**Comment by ilario** [comment]
Amended adding the complete URL

**Pull request merged**
