### PR TITLE
Added comments in configuration files

### PR DESCRIPTION
**Pull request by ilario**
I added some comments in Libre-Mesh configuration files.

### CODE REVIEW

**Comment by altergui** [comment]
Thanks ilario!
the changes to the comments look good,
but there are also changes in the (commented) config which don't :P

i don't see any advantage in including %M in main_ipvX_addresses, since that is already handled by leaving trailing zeroes in a more efficient way (it can use netmasks other than /24 , /16)
in fact, they should include %N instead, so that two different networks get two different ip prefixes by default

at some point in time this used to be
option main_ipv4_address '10.%N1.%N2.0/24'             
option main_ipv6_address 'fddf:ca%N1:%N2%N3:0000::/64' 

anyway, i would leave it untouched for now :)

olsr protocols shouldn't have a vlan id >= 16, since that can clash with batadv protocol (randomly chosen between 16 and 272)

vlans id  < 16 were reserved precisely for hardcoded protocols like this :)

try olsr:14 and olsr6:15  , but in a separate commit ("Add olsr and olsr6 to default protocols list")

**Comment by ilario** [comment]
> i don't see any advantage in including %M in main_ipvX_addresses,

I modified it for making its behaviour explicit, without comments it was obscure.

> since that is already handled by leaving trailing zeroes in a more efficient way (it can use netmasks other than /24 , /16)

Ok, if it's more efficient I'll remove this change :)

> in fact, they should include %N instead, so that two different networks get two different ip prefixes by default

Well, dunno, up to you devs.

> olsr protocols shouldn't have a vlan id >= 16, since that can clash with batadv protocol (randomly chosen between 16 and 272)
> vlans id < 16 were reserved precisely for hardcoded protocols like this :)
> try olsr:14 and olsr6:15 , but in a separate commit ("Add olsr and olsr6 to default protocols list")

Thanks for the suggestion! 
I did put 23 and 24 just because they're the default ones I'm going to put this (with 14,15) in a separate pull request :)

**Comment by G10h4ck** [comment]
> I did put 23 and 24 just because they're the default ones
> I'm going to put this (with 14,15) in a separate pull request :)

**Comment by ilario** [comment]
>> I did put 23 and 24 just because they're the default ones
>> I'm going to put this (with 14,15) in a separate pull request :)

> Nope this should be fixed before merge in both pull request, merge should not introduce know bug 
> then we  have to fix with another pull request fix both pull requests if you want to see them merged ;)

I already removed those lines in afa1645 and 5708dc4 ... What do you mean?

**Comment by G10h4ck** [comment]
It seems to me a good idea to squash is a single commit the whole pull request can you do this ?

**Comment by ilario** [comment]
>  squash [...] commit [...] can you do this ?

No!! But I can try...

**Comment by ilario** [comment]
> squash [...] commit [...] can you do this ?

I think I managed, is this ok?

**Pull request merged**
