### PR TITLE
Including reboot cron command taken from Chef

### PR DESCRIPTION
**Pull request by ilario**
For addressing #61 a solution is a daily reboot.
The file in this pull request comes from Chef (see #50) but Chef includes it with all the lines commented out.

### CODE REVIEW

**Comment by dangowrt** [comment]
I'd rather see a focus on hunting down bugs like that rather than augmenting it with a reboot for another decade. Soon we'll have to reboot every couple of hours, then maybe every 15 minutes? At least try to find specific work-arounds for bugs which cannot be tracked down easily or only occur rarely (the above smells like a locking issue, things as simple as switching on kernel lock debugging via `CONFIG_KERNEL_PROVE_LOCKING` might provide a hint).
Please at least *try* to debug it if your goal is something stable.

**Comment by ilario** [comment]
You're talking to the wrong guy, I'm not the one including this file in Libre-Mesh firmware, it is already there included by Chef. For me having this workaround is ugly, but having it outside lime-packages is much worse. I neither experienced ever the issue #61 and I have no idea how to trigger that. Just trying to get shit in the right place. Or to get a clear decision saying "this is not needed/wanted, please Chef people DON'T add it again, especially not that way".

**Comment by dangowrt** [comment]
Maybe there should then be a group of lime-tweak-XXX packages for each of those files in lime-packages? They could then be individually selected for each build (both, chef and lime-build). I'm just against unconditional inclusion in lime-system.

**Comment by p4u** [comment]
I'm also against including a reboot to the lime-system code. The idea of creating a packet (or several) for this kind of tweaks might be better. In any case I'm pretty sure all of us would prefer to avoid any need of reboot, so let's see if we can debug the problem.

**Comment by ilario** [comment]
> The file in the chef, as you noted, is all commented out ... for a reason! 
> for people that want to enable such behaviour, for whatever reason.

You're right

> i'd vote to leave it in chef as it is

Totally against this option.
Both Chef and lime-build are official ways to obtain the firmware, they can't make images with different contents.

> i think creating a package is overkill

In my opinion the discussion should be on:

- create a package `lime-tweak-periodic-reboot` (as suggested by @dangowrt) with the uncommented file but not contained in lime-basic

or

- include the file in lime-system but in its *commented* version

**Comment by G10h4ck** [comment]
let discuss this stuff here https://github.com/libre-mesh/lime-packages/issues/50 before doing pull requests

**Pull request closed without merging**
